include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_classes_with_only_static_members: false
    avoid_void_async: false
    sort_pub_dependencies: false
    avoid_bool_literals_in_conditional_expressions: false
